from django.urls import path
from .import views 
from .views import InfoPersonalCrearView, VinculoCrearView, SeleccionCrearView, InduccionCrearView, PruebaCrearView, ColegiaturaCrearView, EstudiosCrearView, CursoCrearView, ExperienciaCrearView, MovimientosCrearView, RetencionCrearView, CompensacionesCrearView, EvaluacionCrearView, ProgresionCrearView, DesplazamientoCrearView, ReconocimientoCrearView, LaboralCrearView, SeguridadCrearView, DesvinculacionCrearView

app_name='legajos'

urlpatterns = [
  path('', views.datospersonales_lista, name='datos_personales'),
  path('empleado_crear/', views.empleado_crear, name='empleado_crear'),
  path('info_general/<int:empleado_id>', views.info_general, name='info_general'),
  path('infopersonal/crear/<int:empleado_id>/', InfoPersonalCrearView.as_view(), name='infopersonal_crear'),
  path('infopersonal/editar/<int:infopersonal_id>/', views.infopersonal_editar, name='infopersonal_editar'),
  path('seleccion/crear/<int:empleado_id>/', SeleccionCrearView.as_view(), name='seleccion_crear'),
  path('seleccion/editar/<int:seleccion_id>/', views.seleccion_editar, name='seleccion_editar'),
  path('vinculo/crear/<int:empleado_id>/', VinculoCrearView.as_view(), name='vinculo_crear'),
  path('vinculo/editar/<int:vinculo_id>/', views.vinculo_editar, name='vinculo_editar'),
  path('induccion/crear/<int:empleado_id>/', InduccionCrearView.as_view(), name='induccion_crear'),
  path('induccion/editar/<int:induccion_id>/', views.induccion_editar, name='induccion_editar'),
  path('prueba/crear/<int:empleado_id>/', PruebaCrearView.as_view(), name='prueba_crear'),
  path('prueba/editar/<int:prueba_id>/', views.prueba_editar, name='prueba_editar'),
  path('colegiatura/crear/<int:empleado_id>/', ColegiaturaCrearView.as_view(), name='colegiatura_crear'),
  path('colegiatura/editar/<int:colegiatura_id>/', views.colegiatura_editar, name='colegiatura_editar'),
  path('estudios/crear/<int:empleado_id>/', EstudiosCrearView.as_view(), name='estudios_crear'),
  path('estudios/editar/<int:estudio_id>/', views.estudios_editar, name='estudios_editar'),
  path('curso/crear/<int:empleado_id>/', CursoCrearView.as_view(), name='curso_crear'),
  path('curso/editar/<int:curso_id>/', views.curso_editar, name='curso_editar'),
  path('experiencia/crear/<int:empleado_id>/', ExperienciaCrearView.as_view(), name='experiencia_crear'),
  path('experiencia/editar/<int:experiencia_id>/', views.experiencia_editar, name='experiencia_editar'),
  path('movimientos/crear/<int:empleado_id>/', MovimientosCrearView.as_view(), name='movimientos_crear'),
  path('movimientos/editar/<int:movimientos_id>/', views.movimientos_editar, name='movimientos_editar'),
  path('retencion/crear/<int:empleado_id>/', RetencionCrearView.as_view(), name='retencion_crear'),
  path('retencion/editar/<int:retencion_id>/', views.retencion_editar, name='retencion_editar'),
  path('compensaciones/crear/<int:empleado_id>/', CompensacionesCrearView.as_view(), name='compensaciones_crear'),
  path('compensaciones/editar/<int:compensaciones_id>/', views.compensaciones_editar, name='compensaciones_editar'),
  path('evaluacion/crear/<int:empleado_id>/', EvaluacionCrearView.as_view(), name='evaluacion_crear'),
  path('evaluacion/editar/<int:evaluacion_id>/', views.evaluacion_editar, name='evaluacion_editar'),
  path('progresion/crear/<int:empleado_id>/', ProgresionCrearView.as_view(), name='progresion_crear'),
  path('progresion/editar/<int:progresion_id>/', views.progresion_editar, name='progresion_editar'),
  path('desplazamiento/crear/<int:empleado_id>/', DesplazamientoCrearView.as_view(), name='desplazamiento_crear'),
  path('desplazamiento/editar/<int:desplazamiento_id>/', views.desplazamiento_editar, name='desplazamiento_editar'),
  path('reconocimiento/crear/<int:empleado_id>/', ReconocimientoCrearView.as_view(), name='reconocimiento_crear'),
  path('reconocimiento/editar/<int:reconocimiento_id>/', views.reconocimiento_editar, name='reconocimiento_editar'),
  path('laboral/crear/<int:empleado_id>/', LaboralCrearView.as_view(), name='laboral_crear'),
  path('laboral/editar/<int:laboral_id>/', views.laboral_editar, name='laboral_editar'),
  path('seguridad/crear/<int:empleado_id>/', SeguridadCrearView.as_view(), name='seguridad_crear'),
  path('seguridad/editar/<int:seguridad_id>/', views.seguridad_editar, name='seguridad_editar'),
  path('desvinculacion/crear/<int:empleado_id>/', DesvinculacionCrearView.as_view(), name='desvinculacion_crear'),
  path('desvinculacion/editar/<int:desvinculacion_id>/', views.desvinculacion_editar, name='desvinculacion_editar'),
  path('documentos/', views.documentos, name='documentos'),
  path('dashboard/', views.dashboard, name='dashboard'),
]

