from django.urls import path
from .import views 
from .views import InfoPersonalCrearView, VinculoCrearView, SeleccionCrearView, InduccionCrearView, PruebaCrearView, HabilitacionCrearView, EstudiosCrearView, SerumCrearView, SubespecialidadCrearView, CursoCrearView, ExperienciaCrearView, MovimientosCrearView, RetencionCrearView, CompensacionesCrearView, EvaluacionCrearView, ReconocimientoCrearView, LaboralCrearView, SeguridadCrearView, DesvinculacionCrearView, OtroCrearView

app_name='legajos'

urlpatterns = [
  path('', views.datospersonales_lista, name='datos_personales'),
  path('regimen', views.legajos_lista, name='legajos_lista'),
  path('resolucion_crear/', views.resolucion_crear, name='resolucion_crear'),
  path('resolucion_editar/<int:resolucion_id>', views.resolucion_editar, name='resolucion_editar'),
  path('empleado_crear/', views.empleado_crear, name='empleado_crear'),
  path('historial/<int:empleado_id>/', views.info_historial, name='info_historial'),
  path('empleado_editar/<int:empleado_id>', views.empleado_editar, name='empleado_editar'),
  path('legajos_crear/', views.crear_legajo, name='crear_legajo'),
  path('info_general/<int:legajo_id>', views.info_general, name='info_general'),
  path('infopersonal/crear/<int:legajo_id>/', InfoPersonalCrearView.as_view(), name='infopersonal_crear'),
  path('infopersonal/editar/<int:infopersonal_id>/', views.infopersonal_editar, name='infopersonal_editar'),
  path('seleccion/crear/<int:legajo_id>/', SeleccionCrearView.as_view(), name='seleccion_crear'),
  path('seleccion/editar/<int:seleccion_id>/', views.seleccion_editar, name='seleccion_editar'),
  path('vinculo/crear/<int:legajo_id>/', VinculoCrearView.as_view(), name='vinculo_crear'),
  path('vinculo/editar/<int:vinculo_id>/', views.vinculo_editar, name='vinculo_editar'),
  path('oficina/crear/', views.oficina_crear, name='oficina_crear'),
  path('oficina/editar/<int:oficina_id>/', views.oficina_editar, name='oficina_editar'),
  path('condicion/crear/', views.condicion_crear, name='condicion_crear'),
  path('condicion/editar/<int:condicion_id>/', views.condicion_editar, name='condicion_editar'),
  path('cargo/crear/', views.cargo_crear, name='cargo_crear'),
  path('cargo/editar/<int:cargo_id>/', views.cargo_editar, name='cargo_editar'),
  path('grupo/crear/', views.grupo_crear, name='grupo_crear'),
  path('grupo/editar/<int:grupo_id>/', views.grupo_editar, name='grupo_editar'),
  path('nivel/crear/', views.nivel_crear, name='nivel_crear'),
  path('nivel/editar/<int:nivel_id>/', views.nivel_editar, name='nivel_editar'),
  path('plaza/crear/', views.plaza_crear, name='plaza_crear'),
  path('plaza/editar/<int:plaza_id>/', views.plaza_editar, name='plaza_editar'),
  path('induccion/crear/<int:legajo_id>/', InduccionCrearView.as_view(), name='induccion_crear'),
  path('induccion/editar/<int:induccion_id>/', views.induccion_editar, name='induccion_editar'),
  path('prueba/crear/<int:legajo_id>/', PruebaCrearView.as_view(), name='prueba_crear'),
  path('prueba/editar/<int:prueba_id>/', views.prueba_editar, name='prueba_editar'),
  path('habilitacion/crear/<int:legajo_id>/', HabilitacionCrearView.as_view(), name='habilitacion_crear'),
  path('habilitacion/editar/<int:habilitacion_id>/', views.habilitacion_editar, name='habilitacion_editar'),
  path('estudios/crear/<int:legajo_id>/', EstudiosCrearView.as_view(), name='estudios_crear'),
  path('estudios/editar/<int:estudio_id>/', views.estudios_editar, name='estudios_editar'),
  path('serum/crear/<int:legajo_id>/', SerumCrearView.as_view(), name='serum_crear'),
  path('serum/editar/<int:serum_id>/', views.serum_editar, name='serum_editar'),
  path('subespecialidad/crear/<int:legajo_id>/', SubespecialidadCrearView.as_view(), name='subespecialidad_crear'),
  path('subespecialidad/editar/<int:subespecialidad_id>/', views.subespecialidad_editar, name='subespecialidad_editar'),
  path('curso/crear/<int:legajo_id>/', CursoCrearView.as_view(), name='curso_crear'),
  path('curso/editar/<int:curso_id>/', views.curso_editar, name='curso_editar'),
  path('experiencia/crear/<int:legajo_id>/', ExperienciaCrearView.as_view(), name='experiencia_crear'),
  path('experiencia/editar/<int:experiencia_id>/', views.experiencia_editar, name='experiencia_editar'),
  path('movimientos/crear/<int:legajo_id>/', MovimientosCrearView.as_view(), name='movimientos_crear'),
  path('movimientos/editar/<int:movimientos_id>/', views.movimientos_editar, name='movimientos_editar'),
  path('retencion/crear/<int:legajo_id>/', RetencionCrearView.as_view(), name='retencion_crear'),
  path('retencion/editar/<int:retencion_id>/', views.retencion_editar, name='retencion_editar'),
  path('compensaciones/crear/<int:legajo_id>/', CompensacionesCrearView.as_view(), name='compensaciones_crear'),
  path('compensaciones/editar/<int:compensaciones_id>/', views.compensaciones_editar, name='compensaciones_editar'),
  path('evaluacion/crear/<int:legajo_id>/', EvaluacionCrearView.as_view(), name='evaluacion_crear'),
  path('evaluacion/editar/<int:evaluacion_id>/', views.evaluacion_editar, name='evaluacion_editar'),
  path('reconocimiento/crear/<int:legajo_id>/', ReconocimientoCrearView.as_view(), name='reconocimiento_crear'),
  path('reconocimiento/editar/<int:reconocimiento_id>/', views.reconocimiento_editar, name='reconocimiento_editar'),
  path('laboral/crear/<int:legajo_id>/', LaboralCrearView.as_view(), name='laboral_crear'),
  path('laboral/editar/<int:laboral_id>/', views.laboral_editar, name='laboral_editar'),
  path('seguridad/crear/<int:legajo_id>/', SeguridadCrearView.as_view(), name='seguridad_crear'),
  path('seguridad/editar/<int:seguridad_id>/', views.seguridad_editar, name='seguridad_editar'),
  path('desvinculacion/crear/<int:legajo_id>/', DesvinculacionCrearView.as_view(), name='desvinculacion_crear'),
  path('desvinculacion/editar/<int:desvinculacion_id>/', views.desvinculacion_editar, name='desvinculacion_editar'),
  path('otro/crear/<int:legajo_id>/', OtroCrearView.as_view(), name='otro_crear'),
  path('otro/editar/<int:otro_id>/', views.otro_editar, name='otro_editar'),
  path('documentos/', views.documentos, name='documentos'),
  path('dashboard/', views.dashboard, name='dashboard'),
]

