# Generated by Django 5.1.3 on 2024-12-16 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('dni', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('carnet_extranjeria', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('S', 'Soltero/a'), ('C', 'Casado/a')], max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('modalidad', models.CharField(blank=True, choices=[('CAS', 'CAS'), ('Nombrado', 'Nombrado'), ('Cesante', 'Cesante')], max_length=25)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, choices=[('Amazonas', 'Amazonas'), ('Ancash', 'Ancash'), ('Apurimac', 'Apurimac'), ('Arequipa', 'Arequipa'), ('Ayacucho', 'Ayacucho'), ('Cajamarca', 'Cajamarca'), ('Callao', 'Callao'), ('Cusco', 'Cusco'), ('Huancavelica', 'Huancavelica'), ('Huanuco', 'Huanuco'), ('Ica', 'Ica'), ('Junin', 'Junín'), ('La Libertad', 'La Libertad'), ('Lambayeque', 'Lambayeque'), ('Lima', 'Lima'), ('Loreto', 'Loreto'), ('Madre de Dios', 'Madre de Dios'), ('Moquegua', 'Moquegua'), ('Pasco', 'Pasco'), ('Piura', 'Piura'), ('Puno', 'Puno'), ('San Martin', 'San Martín'), ('Tacna', 'Tacna'), ('Tumbes', 'Tumbes'), ('Ucayali', 'Ucayali')], max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('distrito', models.CharField(blank=True, max_length=50, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
                ('cipss', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BonificacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('anios', models.IntegerField(verbose_name='años')),
                ('meses', models.IntegerField()),
                ('dias', models.IntegerField()),
                ('pdf', models.FileField(upload_to='bonificacion_personal/', verbose_name='Cargar PDF')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajos.datospersonales')),
            ],
            options={
                'verbose_name': 'Bonificación Personal',
                'verbose_name_plural': 'Bonificación Personal',
            },
        ),
        migrations.CreateModel(
            name='AusenciasMeritosDemeritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(max_length=50, unique=True)),
                ('motivo', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=50)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('pdf', models.FileField(upload_to='ausencias_meritos_demeritos/', verbose_name='Cargar PDF')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajos.datospersonales')),
            ],
            options={
                'verbose_name': 'Ausencias, Méritos y Deméritos',
                'verbose_name_plural': 'Ausencias, Méritos y Deméritos',
            },
        ),
        migrations.CreateModel(
            name='EstudiosRealizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('grado_instruccion', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
                ('sub_especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_expedicion', models.DateField()),
                ('pdf', models.FileField(upload_to='estudios_realizados/', verbose_name='Cargar PDF')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajos.datospersonales')),
            ],
            options={
                'verbose_name': 'Estudio Realizado',
                'verbose_name_plural': 'Estudios Realizados',
            },
        ),
        migrations.CreateModel(
            name='PensionistaSobreviviente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(max_length=25, unique=True)),
                ('fecha', models.DateField()),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('pdf', models.FileField(upload_to='pensionista_sobreviviente/', verbose_name='Cargar PDF')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajos.datospersonales')),
            ],
            options={
                'verbose_name': 'Pensionista sobreviviente',
                'verbose_name_plural': 'Pensionista Sobreviviente',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=100)),
                ('codfun', models.CharField(max_length=4)),
                ('codpro', models.CharField(max_length=4)),
                ('codsub', models.CharField(max_length=4)),
                ('codact', models.CharField(max_length=4)),
                ('codcom', models.CharField(max_length=4)),
                ('codmet', models.CharField(max_length=4)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajos.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosPrestados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(blank=True, choices=[('RA', 'Resolución Administrativa'), ('RD', 'Resolución Directoral'), ('Memo', 'Memorando')], max_length=25, null=True)),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número')),
                ('tipo', models.CharField(blank=True, choices=[('Nombramiento', 'Nombramiento'), ('Reasignacion', 'Reasignación'), ('Ascenso', 'Ascenso'), ('Cese', 'Cese')], max_length=15, null=True)),
                ('asunto', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateField()),
                ('fecha_vigencia', models.DateField()),
                ('dependencia', models.CharField(blank=True, choices=[('HHV', 'Hospital Hermilio Valdizán')], max_length=30, null=True)),
                ('pdf', models.FileField(upload_to='servicios_prestados/', verbose_name='Cargar PDF')),
                ('cargo', models.ManyToManyField(blank=True, to='legajos.cargo')),
                ('empleado', models.ManyToManyField(to='legajos.datospersonales')),
                ('nivel', models.ManyToManyField(blank=True, to='legajos.nivel')),
                ('plaza', models.ManyToManyField(blank=True, to='legajos.plaza')),
            ],
            options={
                'verbose_name': 'Servicio Prestado',
                'verbose_name_plural': 'Servicios Prestados',
            },
        ),
        migrations.CreateModel(
            name='TiempodeServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(max_length=50, unique=True)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('anios', models.IntegerField(verbose_name='años')),
                ('meses', models.IntegerField()),
                ('dias', models.IntegerField()),
                ('pdf', models.FileField(upload_to='tiempo_de_servicios/', verbose_name='Cargar PDF')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajos.datospersonales')),
            ],
            options={
                'verbose_name': 'Tiempo de Servicio',
                'verbose_name_plural': 'Tiempo de Servicio',
            },
        ),
    ]
