# Generated by Django 5.1.3 on 2025-03-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleccion',
            name='documento_otro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Especificar otro documento'),
        ),
        migrations.AlterField(
            model_name='infopersonal',
            name='documento',
            field=models.CharField(choices=[('Ficha de datos', 'Ficha de datos'), ('Documento Nacional de Identidad – DNI', 'Documento Nacional de Identidad – DNI'), ('Declaración jurada o Certificado de antecedentes penales', 'Declaración jurada o Certificado de antecedentes penales'), ('Declaración jurada o certificado de antecedentes policiales', 'Declaración jurada o certificado de antecedentes policiales'), ('Declaración Jurada de bienes y rentas', 'Declaración Jurada de bienes y rentas'), ('Declaración Jurada de no tener impedimentos (Ley N° 31419)', 'Declaración Jurada de no tener impedimentos (Ley N° 31419)'), ('Partida de matrimonio o constancia de concubinato', 'Partida de matrimonio o constancia de concubinato'), ('Información de impedimentos e inhabilitaciones', 'Información de impedimentos e inhabilitaciones'), ('DNI de el/la cónyuge o concubino/a', 'DNI de el/la cónyuge o concubino/a'), ('DNI de los/las hijos/as menores de edad', 'DNI de los/las hijos/as menores de edad'), ('Certificado de discapacidad de el/la servidor/a', 'Certificado de discapacidad de el/la servidor/a'), ('Certificado de discapacidad de los/las hijos/as', 'Certificado de discapacidad de los/las hijos/as'), ('Declaración Jurada por Nepotismo', 'Declaración Jurada por Nepotismo'), ('Otro Documento', 'Otro Documento')], max_length=100, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='infopersonal',
            name='documento_otro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Especificar otro documento'),
        ),
        migrations.AlterField(
            model_name='seleccion',
            name='documento',
            field=models.CharField(choices=[('Resultado Final de proceso de selección', 'Resultado Final de proceso de selección'), ('Informe de la Oficina de Personal', 'Informe de la Oficina de Personal'), ('Otro Documento', 'Otro Documento')], max_length=100, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='tipo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Nombramiento'), (20, 'Contrato Administrativo de Servicios'), (30, 'Contrato a plazo fijo'), (40, 'Destaque de otra Dependencia'), (50, 'Designación de otra Dependencia')], null=True),
        ),
    ]
