# Generated by Django 5.1.3 on 2025-03-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='duracion',
        ),
        migrations.AddField(
            model_name='curso',
            name='centro',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Centro de Estudios'),
        ),
        migrations.AddField(
            model_name='curso',
            name='creditos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='horas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiosrealizados',
            name='centro',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Centro de Estudios'),
        ),
        migrations.AddField(
            model_name='estudiosrealizados',
            name='colegiatura',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='subespecialidad',
            name='centro',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Centro de Estudios'),
        ),
    ]
