# Generated by Django 5.1.3 on 2025-01-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo',
            name='cargo',
            field=models.ManyToManyField(blank=True, to='legajos.cargo'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='nivel',
            field=models.ManyToManyField(blank=True, to='legajos.nivel'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='plaza',
            field=models.ManyToManyField(blank=True, to='legajos.plaza'),
        ),
    ]
