# Generated by Django 5.1.3 on 2024-12-29 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datospersonales',
            options={'ordering': ['apellido_paterno'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
