# Generated by Django 5.1.3 on 2025-01-26 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.PositiveSmallIntegerField(choices=[(5, 'Reconocimiento'), (10, 'Sanción')], verbose_name='Reconocimientos y Sanciones')),
                ('documento', models.PositiveSmallIntegerField(choices=[(5, 'Resolución Administrativa'), (10, 'Resolución Directoral'), (15, 'Memorando')], verbose_name='Tipo de Documento')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('pdf', models.FileField(upload_to='documentos_reconocimiento/', verbose_name='Cargar PDF')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajos.datospersonales')),
            ],
            options={
                'verbose_name': 'Reconocimientos y Sanciones',
                'verbose_name_plural': 'Reconocimientos y Sanciones',
                'ordering': ['tipo_documento'],
            },
        ),
    ]
