# Generated by Django 5.1.3 on 2025-02-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='modalidad',
        ),
        migrations.RemoveField(
            model_name='retencion',
            name='fecha_carga',
        ),
        migrations.AddField(
            model_name='retencion',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
