# Generated by Django 5.1.3 on 2025-03-17 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0002_remove_curso_duracion_curso_centro_curso_creditos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Colegiatura',
            new_name='Habilitacion',
        ),
        migrations.AlterModelOptions(
            name='habilitacion',
            options={'ordering': ['documento', '-fecha_emision'], 'verbose_name': 'Habilitación Profesional', 'verbose_name_plural': 'Habilitación Profesional'},
        ),
    ]
