# Generated by Django 5.1.3 on 2025-01-05 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0002_alter_vinculo_cargo_alter_vinculo_nivel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinculo',
            options={'verbose_name': 'Formalización de Vínculo', 'verbose_name_plural': 'Formalización de Vínculo'},
        ),
        migrations.AlterField(
            model_name='infopersonal',
            name='tipo_documento',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Ficha de datos'), (6, 'Documento Nacional de Identidad – DNI'), (9, 'Declaración jurada o Certificado de antecedentes penales'), (12, 'Declaración jurada o certificado de antecedentes policiales'), (15, 'Declaración Jurada de bienes y rentas'), (18, 'Declaración Jurada de no tener impedimentos (Ley N° 31419)'), (21, 'Partida de matrimonio o constancia de concubinato'), (24, 'Información de impedimentos e inhabilitaciones'), (27, 'DNI de el/la cónyuge o concubino/a'), (30, 'DNI de los/las hijos/as menores de edad'), (33, 'Certificado de discapacidad de el/la servidor/a'), (36, 'Certificado de discapacidad de los/las hijos/as')], verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='seleccion',
            name='tipo_documento',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Resultado Final de proceso de selección'), (6, 'Informe de la Oficina de Personal')], verbose_name='Tipo de Documento'),
        ),
        migrations.CreateModel(
            name='Induccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.PositiveSmallIntegerField(choices=[(3, 'Ficha de datos'), (6, 'Documento Nacional de Identidad – DNI'), (9, 'Declaración jurada o Certificado de antecedentes penales'), (12, 'Declaración jurada o certificado de antecedentes policiales'), (15, 'Declaración Jurada de bienes y rentas'), (18, 'Declaración Jurada de no tener impedimentos (Ley N° 31419)'), (21, 'Partida de matrimonio o constancia de concubinato'), (24, 'Información de impedimentos e inhabilitaciones'), (27, 'DNI de el/la cónyuge o concubino/a'), (30, 'DNI de los/las hijos/as menores de edad'), (33, 'Certificado de discapacidad de el/la servidor/a'), (36, 'Certificado de discapacidad de los/las hijos/as')], verbose_name='Tipo de Documento')),
                ('pdf', models.FileField(upload_to='documentos_empleados/', verbose_name='Cargar PDF')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajos.datospersonales')),
            ],
            options={
                'verbose_name': 'Inducción del Personal',
                'verbose_name_plural': 'Inducción del Personal',
                'ordering': ['tipo_documento'],
                'unique_together': {('empleado', 'tipo_documento')},
            },
        ),
    ]
