# Generated by Django 5.1.3 on 2024-12-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0002_alter_datospersonales_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciosprestados',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
