# Generated by Django 5.1.3 on 2025-02-25 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0002_remove_empleado_modalidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='fecha_carga',
        ),
    ]
