# Generated by Django 5.1.3 on 2025-01-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0002_reconocimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconocimiento',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
