# Generated by Django 5.1.3 on 2025-03-17 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0003_rename_colegiatura_habilitacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habilitacion',
            options={'ordering': ['registro', '-fecha_emision'], 'verbose_name': 'Habilitación Profesional', 'verbose_name_plural': 'Habilitación Profesional'},
        ),
        migrations.RemoveField(
            model_name='habilitacion',
            name='documento',
        ),
        migrations.AddField(
            model_name='habilitacion',
            name='registro',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Número de Registro'),
        ),
        migrations.AlterField(
            model_name='habilitacion',
            name='fecha_emision',
            field=models.DateField(verbose_name='Fecha de Emisión'),
        ),
        migrations.AlterField(
            model_name='habilitacion',
            name='pdf',
            field=models.FileField(upload_to='documentos_habilitacion/', verbose_name='Cargar PDF'),
        ),
        migrations.AlterField(
            model_name='subespecialidad',
            name='pdf',
            field=models.FileField(upload_to='formacion_especialidad/', verbose_name='Cargar PDF'),
        ),
        migrations.CreateModel(
            name='Serum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(blank=True, max_length=25, null=True, verbose_name='Número de Registro')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('pdf', models.FileField(upload_to='documentos_serum/', verbose_name='Cargar PDF')),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajos.legajo')),
            ],
            options={
                'verbose_name': 'SERUM',
                'verbose_name_plural': 'SERUM',
                'ordering': ['registro', '-fecha_emision'],
            },
        ),
    ]
