# Generated by Django 5.1.3 on 2025-01-26 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0003_reconocimiento_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.PositiveSmallIntegerField(choices=[(5, 'Controversias Individuales'), (10, 'Controversias Colectivas'), (15, 'Afiliación al Sindicato')], verbose_name='Relaciones Laborales')),
                ('documento', models.PositiveSmallIntegerField(choices=[(5, 'Resolución Administrativa'), (10, 'Resolución Directoral'), (15, 'Memorando')], verbose_name='Tipo de Documento')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('pdf', models.FileField(upload_to='documentos_laboral/', verbose_name='Cargar PDF')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajos.datospersonales')),
            ],
            options={
                'verbose_name': 'Relaciones Laborales',
                'verbose_name_plural': 'Relaciones Laborales',
                'ordering': ['tipo_documento'],
            },
        ),
    ]
