# Generated by Django 5.1.3 on 2025-01-06 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0003_alter_vinculo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonificacionpersonal',
            name='empleado',
        ),
        migrations.AlterModelOptions(
            name='estudiosrealizados',
            options={'ordering': ['-fecha_expedicion'], 'verbose_name': 'Estudio Realizado', 'verbose_name_plural': 'Estudios Realizados'},
        ),
        migrations.AlterModelOptions(
            name='vinculo',
            options={'ordering': ['-fecha'], 'verbose_name': 'Formalización de Vínculo', 'verbose_name_plural': 'Formalización de Vínculo'},
        ),
        migrations.AlterField(
            model_name='estudiosrealizados',
            name='pdf',
            field=models.FileField(upload_to='formacion_academica/', verbose_name='Cargar PDF'),
        ),
        migrations.AlterField(
            model_name='induccion',
            name='pdf',
            field=models.FileField(upload_to='documentos_induccion/', verbose_name='Cargar PDF'),
        ),
        migrations.AlterField(
            model_name='induccion',
            name='tipo_documento',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Registro de Inducción'), (6, 'Cargo de entrega de perfil de puesto y funciones'), (9, 'Cargo de entrega de reglamento interno de servidores civiles'), (12, 'Cargo de entrega de código de conducta y ética')], verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='infopersonal',
            name='pdf',
            field=models.FileField(upload_to='documentos_personales/', verbose_name='Cargar PDF'),
        ),
        migrations.AlterField(
            model_name='seleccion',
            name='pdf',
            field=models.FileField(upload_to='documentos_seleccion/', verbose_name='Cargar PDF'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='pdf',
            field=models.FileField(upload_to='documentos_vinculo/', verbose_name='Cargar PDF'),
        ),
        migrations.CreateModel(
            name='Compensaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('anios', models.IntegerField(verbose_name='años')),
                ('meses', models.IntegerField()),
                ('dias', models.IntegerField()),
                ('pdf', models.FileField(upload_to='compensaciones/', verbose_name='Cargar PDF')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajos.datospersonales')),
            ],
            options={
                'verbose_name': 'Bonificación Personal',
                'verbose_name_plural': 'Bonificación Personal',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('descripcion', models.CharField(max_length=250)),
                ('duracion_horas', models.IntegerField()),
                ('fecha_expedicion', models.DateField()),
                ('pdf', models.FileField(upload_to='cursos/', verbose_name='Cargar PDF')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajos.datospersonales')),
            ],
            options={
                'verbose_name': 'Especializaciones, Diplomados, Cursos, Talleres',
                'verbose_name_plural': 'Especializaciones, Diplomados, Cursos, Talleres',
                'ordering': ['-fecha_expedicion'],
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('descripcion', models.CharField(max_length=250)),
                ('pdf', models.FileField(upload_to='experiencia_laboral/', verbose_name='Cargar PDF')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajos.datospersonales')),
            ],
            options={
                'verbose_name': 'Especializaciones, Diplomados, Cursos, Talleres',
                'verbose_name_plural': 'Especializaciones, Diplomados, Cursos, Talleres',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(max_length=50, unique=True)),
                ('motivo', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=50)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('pdf', models.FileField(upload_to='movimientos_personal/', verbose_name='Cargar PDF')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajos.datospersonales')),
            ],
            options={
                'verbose_name': 'Movimientos del Personal',
                'verbose_name_plural': 'Movimientos del Personal',
            },
        ),
        migrations.DeleteModel(
            name='AusenciasMeritosDemeritos',
        ),
        migrations.DeleteModel(
            name='BonificacionPersonal',
        ),
    ]
