# Generated by Django 5.1.3 on 2025-01-27 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0004_laboral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.PositiveSmallIntegerField(choices=[(5, 'Cargo de entrega del Reglamento de SST'), (10, 'Registro de entrenamiento, y simulacros de emergencias'), (15, 'Capacitaciones brindadas por la entidad'), (20, 'Trámites y gestiones de seguro'), (25, 'Trámites y gestiones de subsidios'), (30, 'Descanso Médico'), (35, 'Afiliaciones a Entidades Prestadoras de Salud (EPS)')], verbose_name='SST y Bienestar social')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('pdf', models.FileField(upload_to='documentos_sst/', verbose_name='Cargar PDF')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajos.datospersonales')),
            ],
            options={
                'verbose_name': 'SST y Bienestar social',
                'verbose_name_plural': 'SST y Bienestar social',
                'ordering': ['tipo_documento'],
            },
        ),
    ]
