# Generated by Django 5.1.3 on 2025-03-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0004_alter_habilitacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ['periodo', 'anio'], 'verbose_name': 'Evaluación de Desempeño', 'verbose_name_plural': 'Evaluación de Desempeño'},
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='anio',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='estudiosrealizados',
            name='grado_instruccion',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Secundaria Completa'), (20, 'Superior Técnica Incompleta'), (30, 'Superior Técnica'), (40, 'Superior Universitario Incompleta'), (50, 'Superior Universitario'), (60, 'Maestría'), (70, 'Doctorado')], verbose_name='Grado de Instrucción'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='periodo',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II')], max_length=50),
        ),
    ]
