# Generated by Django 5.1.3 on 2025-01-27 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0005_seguridad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desvinculacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.PositiveSmallIntegerField(choices=[(5, 'Resolución de término de designación'), (10, 'Resolución de término del servicio civil de carrera'), (15, 'Memorando  de término de vínculo del servicio civil'), (20, 'Informe de Gestión'), (25, 'Entrega de cargo/puesto'), (30, 'Liquidación de beneficios sociales y/o pensión'), (35, 'Carta de no renovación de contrato a plazo determinado')], verbose_name='Desvinculación')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('pdf', models.FileField(upload_to='documentos_desvinculacion/', verbose_name='Cargar PDF')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajos.datospersonales')),
            ],
            options={
                'verbose_name': 'Desvinculación',
                'verbose_name_plural': 'Desvinculación',
                'ordering': ['tipo_documento'],
            },
        ),
    ]
