# Generated by Django 5.1.3 on 2024-12-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantillareporte',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='plantillareporte',
            name='tipo',
            field=models.CharField(choices=[('constancia', 'Constancia de Trabajo'), ('escalafonario', 'Informe Escalafonario')], default='constancia', max_length=50),
        ),
    ]
